# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-17 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
