# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_emo', '0002_corpustext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpustext',
            name='corpus_emo',
            field=models.TextField(),
        ),
    ]
