# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-23 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text_emo', '0003_auto_20200317_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpustext',
            name='corpus_Num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
