# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_emo', '0004_corpustext_corpus_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpustext',
            name='corpus_Num',
            field=models.TextField(),
        ),
    ]
