# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_emo', '0005_auto_20200323_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='corpus',
            fields=[
                ('corpus_ID', models.AutoField(primary_key=True, serialize=False)),
                ('corpus_Num', models.IntegerField()),
                ('corpus_emo', models.TextField()),
                ('corpus_content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CorpusText',
        ),
    ]
